### ISSUE TITLE
Implémentation de requêtes spécifiques - partie 2

### ISSUE THREAD

**Issue by loannchhum** [BOURREAUQuentin/Festiut-O#13]
idBillet -> liste Evenement 
idSpectateur -> liste Groupe (pour page favori)
nomStyleMusical -> liste Groupe (faisant partie du style pour une recherche)

**Comment by BOURREAUQuentin** [comment]
1er requete réalisée : lister_evenements_pour_billet
2eme requete réalisée : lister_groupes_favoris_pour_spectateur
3eme requete réalisée : rechercher_groupes_par_style_musical
