### ISSUE TITLE
Ajouter des requêtes pour le panier

### ISSUE THREAD

**Issue by MaverickPrevost** [BOURREAUQuentin/Festiut-O#20]
- vider le panier
- changer la quantite
- ajouter le billet dans la BD
- etc...

**Comment by BOURREAUQuentin** [comment]
en attente actuel car tu veux les requetes pour billetterie d'abord

**Comment by BOURREAUQuentin** [comment]
j'ai ajouté un attribut quantiteB pour la quantité au panier d'un billet et j'ai fait les requetes pour ajouter un billet au panier, modifier la quantité d'un billet, supprimer un billet au panier et payer le panier. Je finis la prochaine fois sur le calcul du prix du panier

**Comment by BOURREAUQuentin** [comment]
j'ai fini toutes les requetes pour le panier avec la route qui est prête pour la template
