### ISSUE TITLE
Préparer les requetes et la route pour la page profil

### ISSUE THREAD

**Issue by loannchhum** [BOURREAUQuentin/Festiut-O#45]

**Comment by BOURREAUQuentin** [comment]
j'ai préparé la page profil avec la route. J'ai ajouté aussi le fait que lorsqu'un billet est déjà dans le panier d'un spectateur et qu'on l'ajoute à nouveau au panier ca actualise sa quantité (+1) et de même lorsque le spectateur a déjà payé un billet (ex: Samedi) et qu'il paye de nouveau ce billet (Samedi) cela actualise la quantité du billet acheté (ici 2 au lieu d'1).
