### ISSUE TITLE
Ajouter fonctionnalités application

### ISSUE THREAD

**Issue by loannchhum** [BOURREAUQuentin/Festiut-O#62]
chiffrer mdp
rendre visible/invisible mdp

**Comment by BOURREAUQuentin** [comment]
pour l'instant j'ai fait : 
- chiffrage du mdp
- amélioration popup d'erreur qui reset pas les données entrées (inscription)
- popup erreur quand le spectateur n'a pas 18ans
- ajout insertions
- ajout requete pour modifier les infos du spectateur

**Comment by BOURREAUQuentin** [comment]
j'ai fait aussi cacher/rendre visible mdp
